spring:
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
  jpa:
   properties:
    hibernate:
     jdbc:
      time_zone: UTC
   hibernate:
      naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
   datasource:
    hikari:
     leakDetectionThreshold: 2000
     connectionTimeout: 30000
     idleTimeout: 600000
     maxLifetime: 1800000 
     minimumIdle: 3
     maximumPoolSize: 10
     connection-test-query: SELECT 1 FROM DUAL
  cloud:
    config:
      uri: http://config-server:8051,http://localhost:8051
management:
    endpoints:
      web:
        exposure:
          include: "*"
          
            
