spring: 
  datasource: 
    password: ENC(MJ02YXylRfAjKRmU4G5dyoTWbP1FuWYp)
    url: jdbc:mysql://database-1.ckvoov2dqnim.us-east-1.rds.amazonaws.com:3306/customerdb
    username: admin
feign:
  hystrix:
    enabled: true